"""
Script to inspect database records and distinguish between original seeded dataset records and test/audit verification records.
"""

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from src.database.connection import SessionLocal
from src.database.models import TransactionModel, PredictionModel, AlertModel

def inspect_database_records():
    print("=" * 70)
    print("DATABASE TEST/DEMO RECORD AUDIT")
    print("=" * 70)

    db = SessionLocal()
    try:
        all_txs = db.query(TransactionModel.transaction_id).all()
        tx_ids = [t[0] for t in all_txs]

        seeded_txs = [tid for tid in tx_ids if tid.isdigit() or (tid.startswith("T") and tid[1:].isdigit() and int(tid[1:]) <= 5000)]
        test_txs = [tid for tid in tx_ids if not (tid.isdigit() or (tid.startswith("T") and tid[1:].isdigit() and int(tid[1:]) <= 5000))]

        print(f"Total Transactions in DB: {len(tx_ids)}")
        print(f"Original Seeded Dataset Transactions: {len(seeded_txs)}")
        print(f"Test / Verification Generated Transactions: {len(test_txs)}")
        print("\nIdentified Test / Verification Transaction IDs:")
        for t in test_txs:
            print(f"  - {t}")

        # Check Alerts associated with test transactions
        test_alerts = db.query(AlertModel).filter(AlertModel.transaction_id.in_(test_txs)).all()
        print(f"\nAlerts generated by test transactions: {len(test_alerts)}")
        for a in test_alerts:
            print(f"  - Alert ID {a.id} (Tx: {a.transaction_id}, Severity: {a.severity}, Status: {a.status})")

    finally:
        db.close()

if __name__ == "__main__":
    inspect_database_records()
